version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        networks:
            - app-network

    db:
        image: postgres:13
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database_name
        ports:
            - '5432:5432'
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-network

    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
